version: '3.8'

volumes:
    logs:
        driver: local
    mysql_data:
        driver: local

services:
    php:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: slim_php
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: slim_laravel_dev
            DB_USERNAME: root
            DB_PASSWORD: secret
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: slim_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: slim_laravel_dev
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_USER: slim
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
